name: movieapp
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0  
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.7.0  
  image_picker: ^1.1.2
  provider: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/June.jpg
    - assets/Avengers Endgame.jpg
    - assets/Batman.jpg
    - assets/Arcane.jpg
    - assets/Arcane(2).png
    - assets/Loki.png
    - assets/Stranger Things.jpg
    - assets/Adventure Time.jpg
    - assets/Gravity Falls.jpeg
    - assets/Rick and Morty.jpg
    - assets/Star vs the Forces of Evil.jpg
    - assets/Frozen 2.png
    - assets/Frozen 2(2).png
    - assets/Decendants.png
    - assets/Ambut.png
    - assets/Run On.png

    - assets/Verification boy.png
    - assets/Home Button.png
    - assets/Library Button.png
    - assets/Notification Button.png
    - assets/Popcorn.png
    - assets/Account Button.png
    - assets/Book.png
    - assets/Bookmark Icon.png
    - assets/Star.png
fonts:
    - family: MuseoModerno
      fonts:
        - asset: assets/fonts/MuseoModerno-Regular.ttf
        - asset: assets/fonts/MuseoModerno-Bold.ttf
        - asset: assets/fonts/MuseoModerno-Black.ttf
          weight: 900
